apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: skydive-analyzer
  name: skydive-analyzer-config
  namespace: skydive
data:
  SKYDIVE_ANALYZER_FLOW_BACKEND: elasticsearch
  SKYDIVE_ANALYZER_TOPOLOGY_BACKEND: elasticsearch
  SKYDIVE_ANALYZER_TOPOLOGY_PROBES: k8s
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: skydive-analyzer
  name: skydive-analyzer-config-etc-skydive
  namespace: skydive
data:
  skydive.yml: |
    http:
      ws:
        ping_delay: 120
        pong_timeout: 180
    agent:
      topology:
        probes:
          - ovsdb
          - docker
          - runc
      runc:
        run_path:
        - /var/run/runc
        - /var/run/runc-ctrs
    analyzer:
      listen: 0.0.0.0:8082